version: "3.1"
volumes:
  grafana:
  postgres:
services:
  agent:
    image: grafana/agent:main
    ports:
      - "4318:4318"
    volumes:
      - "./grafana_agent/config.yaml:/etc/agent/agent.yaml"

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo
    ports:
      - "4317:4317"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./grafana_tempo/tempo-local.yaml:/etc/tempo.yaml

  fastapi_server:
    image: fastapi_server_image
    build:
      context: ./fastapi_app/
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - tempo
      - loki

  fastapi_server_polling_service:
    image: fastapi_server_polling_service_image
    build:
      context: ./python_scripts/
      dockerfile: Dockerfile
    depends_on:
      - fastapi_server
